# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opentox-validation-lib}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Guetlein"]
  s.date = %q{2009-11-02}
  s.description = %q{Ruby lib for the OpenTox REST VALIDATION API}
  s.email = %q{guetlein@informatik.uni-freiburg.de}
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/opentox-validation-lib.rb",
     "lib/prediction_util.rb",
     "lib/prediction_util.rb",
     "lib/test_util.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/guetlein/opentox-validation-lib}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Ruby lib for the OpenTox REST VALIDATION API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
  end
end
